# Generated by Django 4.1.4 on 2023-01-20 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_message_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='lieu',
            field=models.CharField(choices=[('1', 'Tunis'), ('2', 'Monastir'), ('3', 'Gabes'), ('4', 'Medenin'), ('5', 'Sousse'), ('6', 'Binzert'), ('7', 'Sfax'), ('8', 'Tozeur'), ('9', 'Tataouine'), ('10', 'Mahdia'), ('11', 'Kairouan'), ('12', 'BenArous'), ('13', 'Gafsa'), ('14', 'Jendouba'), ('15', 'El kef'), ('16', 'Ariana'), ('17', 'Kasserine'), ('18', 'SidiBouzid'), ('19', 'beja'), ('20', ' Zagouan'), ('21', 'seliana'), ('22', 'kebili'), ('23', 'Manouba'), ('24', 'Nabeul')], max_length=20, null=True),
        ),
    ]
