# Generated by Django 4.1.4 on 2023-01-20 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_room_lieu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='lieu',
            new_name='location',
        ),
    ]
