# Generated by Django 4.1.4 on 2023-01-20 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_lieu_room_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='location',
            field=models.CharField(choices=[('Tunis', ''), ('Monastir', ''), ('Gabes', ''), ('Medenin', ''), ('Sousse', ''), ('Binzert', ''), ('Sfax', ''), ('Tozeur', ''), ('Tataouine', ''), ('Mahdia', ''), ('Kairouan', ''), ('BenArous', ''), ('Gafsa', ''), ('Jendouba', ''), ('El kef', ''), ('Ariana', ''), ('Kasserine', ''), ('SidiBouzid', ''), ('beja', ''), ('Zagouan', ''), ('seliana', ''), ('kebili', ''), ('Manouba', ''), ('Nabeul', '')], max_length=20, null=True),
        ),
    ]
