# Generated by Django 4.1.4 on 2023-01-22 23:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0009_room_liked_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='liked',
        ),
        migrations.AddField(
            model_name='room',
            name='likes',
            field=models.ManyToManyField(related_name='post', to=settings.AUTH_USER_MODEL),
        ),
    ]
