# Generated by Django 4.1.4 on 2023-01-22 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_remove_room_liked_room_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
