# Generated by Django 4.1.4 on 2023-01-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_room_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='location',
            field=models.CharField(choices=[('Tunis', 'TUNIS'), ('Monastir', 'MONASTIR'), ('Gabes', 'GABES'), ('Medenin', 'MEDENIN'), ('Sousse', 'SOUSSE'), ('Binzert', 'BINZERT'), ('Sfax', 'SFAX'), ('Tozeur', 'TOZEUR'), ('Tataouine', 'TATAOUINE'), ('Mahdia', 'MAHDIA'), ('Kairouan', 'KAIROUAN'), ('BenArous', 'BENAROUS'), ('Gafsa', 'GAFSA'), ('Jandouba', 'JANDOUBA'), ('El kef', 'ELKEF'), ('Ariana', 'ARIANA'), ('Kasserine', 'KASERINE'), ('SidiBouzid', 'SIDIBOUZID'), ('beja', 'BEJA'), ('Zagouen', 'ZAGOUEN'), ('seliana', 'SELIANA'), ('kebili', 'KEBILI'), ('Manouba', 'MANOUBA'), ('Nabeul', 'NABEUL')], max_length=20, null=True),
        ),
    ]
