# Generated by Django 4.1.4 on 2023-01-25 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_room_avgrate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='avgrate',
        ),
    ]
