# Generated by Django 4.1.4 on 2023-01-26 23:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0018_alter_message_image_alter_room_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Room',
            new_name='Museum',
        ),
    ]
